mysql:
  datasource:
    druid:
      ## 驱动
      driverClassName: com.mysql.cj.jdbc.Driver
      ## 数据源类型
      type: com.alibaba.druid.pool.DruidDataSource
      ## 数据库链接URL
      url: jdbc:mysql://localhost:3306/db_qa_mba?useSSL=false&allowPublicKeyRetrieval=true&serverTimeZone=Asia/Shanghai
      ## 数据库账户
      username: test
      ## 数据库密码
      password: 123456
      ## 连接池建立时创建的初始化连接数
      initialSize: 5
      ## 连接池中最大的活跃连接数
      maxActive: 20
      ## 连接池中最小的活跃连接数
      minIdle: 5
      ## 获取连接等待超时的时间
      maxWait: 60000
      ## 空闲连接回收器线程休眠的时间值
      timeBetweenEvictionRunsMillis: 60000
      ## 连接池中的空闲连接保持空闲不被空闲连接回收器线程回收的最小时间值
      minEvictableIdleTimeMillis: 300000
      ## 是否打开PSCache
      poolPreparedStatements: true
      ## 每个连接上PSCache的大小
      maxPoolPreparedStatementPerConnectionSize: 20
      ## 是否在获得连接后检测其可用性
      testOnBorrow: false
      ## 是否在连接放回连接池后检测其可用性
      testOnReturn: false
      ## 是否在连接空闲一段时间后检测其可用性
      testWhileIdle: true
      ## 检测连接是否有效的SQL语句
      validationQuery: SELECT 1 FROM DUAL
      ## 验证连接有效性的超时时间
      validationQueryTimeout: 30000
      ## 拓展字符集支持Emoji
      connectionInitSqls: 'set names utf8mb4;'

mybatis:
  ## mapper.xml文件放置的位置
  mapper-locations: classpath:mapper/**/*.xml