spring:
  profiles:
    include: localMysql

## Redis连接配置
spring.redis.host: localhost
spring.redis.port: 6379
## 服务器
server:
  ## 域名
  domain: http://localhost
  ## 端口
  port: 14040

## netty
netty:
  ## 端口
  port: 9999
